### ISSUE TITLE
Create user survey visuals

### ISSUE THREAD

**Issue by manolobevia** [cul-it/wp-cul-main#20]
Interactive user survey flow samples in sketch app.
[CUL-banner-survey.zip](https://github.com/cul-it/wp-cul-main/files/7008905/CUL-banner-survey.zip)

**Comment by manolobevia** [comment]
## Top banner survey sample 1
![Top Banner Survey v1 1](https://user-images.githubusercontent.com/8395482/129940490-7356a3c8-716e-488a-b52f-2641e3a63cae.png)

##

![Top Banner Survey Feedback v1 2](https://user-images.githubusercontent.com/8395482/129940513-45386701-e4f3-4274-ab13-bf1a5f701707.png)

**Comment by manolobevia** [comment]
## Top banner survey sample 2
![Top Banner Survey v2 1](https://user-images.githubusercontent.com/8395482/129940744-372cbbd2-29db-4dea-9041-d9de817cd48e.png)


##

![Top Banner Survey v2 2](https://user-images.githubusercontent.com/8395482/129940762-fb323a45-1759-49e1-863f-fc8ccab79105.png)

**Comment by manolobevia** [comment]
## Top banner survey sample 3

![Top Banner Survey v3 1](https://user-images.githubusercontent.com/8395482/129940819-bf3a89ad-e322-49eb-b578-52fe2e6adef1.png)

##

![Top Banner Survey v3 2](https://user-images.githubusercontent.com/8395482/129940827-e33465c4-d4db-41fc-8873-6386f18c1fdb.png)

**Comment by manolobevia** [comment]
## Bottom banner survey sample 1

![Bottom Banner Survey v1 1](https://user-images.githubusercontent.com/8395482/129940941-238707ce-29f1-4cb0-9684-fbaa5122340e.png)

##

![Bottom Banner Survey Feedback v1 2](https://user-images.githubusercontent.com/8395482/129940966-d2717a93-24a9-4b83-82cf-5059334ef8c8.png)

**Comment by manolobevia** [comment]
## Bottom banner survey sample 2

![Bottom Banner Survey v2 1](https://user-images.githubusercontent.com/8395482/129941067-c6483777-56e4-4f60-a8f1-67abf4ec71b8.png)


##

![Bottom Banner Survey Feedback v2 2](https://user-images.githubusercontent.com/8395482/129941097-05b65dab-df0f-4607-b6de-f6b5a4ea96e1.png)

**Comment by manolobevia** [comment]
I will work on mobile versions once I get feedback for the desktop versions above.
Thanks.

**Comment by kevinkidwell** [comment]
I really like the unobtrusive nature of the corner pop-up and would honestly prefer to just do something like that instead of a full screen takeover if we could. This would be the ideal if we could get it implemented this way but I don't know about the accessibility that would need to be done to make it work (focus, trapping, keyboard navigation, etc.).

If we did this as a header banner, I would have expected it to be above the branding and then track with a user as they scroll down the page.

I'm not fond of the footer banner because it just gets too easy for a user to ignore.

**Comment by mhk33** [comment]
Thanks, Manolo, these look great! I like the bottom survey sample 2 the best. I think Zsuzsa may have issue with the CUL logo covered up by the top survey option.

**Comment by manolobevia** [comment]
@dbranchini Here goes the chosen one. Please let me know if you need anything else.

![Survey - Flow 1](https://user-images.githubusercontent.com/8395482/130108621-3351a46c-8f65-4705-9cdd-c17fa4255287.png)

##

![Survey - Flow 2](https://user-images.githubusercontent.com/8395482/130108639-6dd0587f-599b-4388-a43c-4a4593f7b05b.png)
