### ISSUE TITLE
Review graduate students survey

### ISSUE THREAD

**Issue by dbranchini** [cul-it/wp-cul-main#23]

**Comment by sew268** [comment]
Consistent areas mentioned where support was needed:

- finding research information/resources
- finding primary source materials
- organizing research
- digital resources
- finding materials for teaching
- VPN/Passkey
- Data Management
- Citation Management

Useful comments regarding the website as we move forward:

- information overload on the main site
- more thorough website menu
- need for stacks maps/floor maps
- easier login to passkey
- browsing/finding similar resources 

why go to library?
Olin:
books, graduate lounge, hours, more seating, cafe, convenience, printing, carrel/locker, new & noteworthy, pick up items (hold requests, BD, ILL)
Mann: 
all same as above but also - consultation services, software/computing, reservable spaces, group and quiet study, 

Additional suggestions: 
offering basic tutorials on zotero, more group and reservable spaces

Melissa's notes:

- very research focused - research organization, finding resources
- citation management - more organizing resources once you find them
- data management
- some systemic reviews
- passkey/online access to resources
- access to materials
- book delivery
- where to find books in subject area
- want more books in stacks, not annex
- information overload
- unclear to me what website they are talking about - could be main site, catalog, others, as a whole

my take: too much information presented, too many options to get there via navigation or redundant pages; cleaner presentation of research help and resource management
