### ISSUE TITLE
Obtain Mann website redesign user research/reports

### ISSUE THREAD

**Issue by dbranchini** [cul-it/wp-cul-main#4]

**Comment by dbranchini** [comment]
Won't Do

**Comment by dbranchini** [comment]
I found usability tasks:
[User Testing Tasks Round 4](https://github.com/cul-it/mann-wagon/issues/552)
[User Testing Tasks Round 2](https://github.com/cul-it/mann-wagon/issues/218)
[User Testing Tasks Round 1 - Secondary](https://github.com/cul-it/mann-wagon/issues/124)
[User Testing Tasks Round 1 - Priority](https://github.com/cul-it/mann-wagon/issues/114)
[Staff Usability Tasks](https://github.com/cul-it/mann-wagon/issues/373)

Miscellaneous:
[Reservation Availability Task](https://github.com/cul-it/mann-wagon/issues/109)
[Events Task](https://github.com/cul-it/mann-wagon/issues/108)
[Search Task](https://github.com/cul-it/mann-wagon/issues/107)
[Specialty Task](https://github.com/cul-it/mann-wagon/issues/106)

**Comment by sew268** [comment]
I was able to find some notes from the staff user testing: https://docs.google.com/document/d/1m3Vjl45qe85iha_U0E59CRHwufAx6Vlu7PK1cmjwzx0/edit?usp=sharing.  

That's all I have in terms of notes - I've looked everywhere and can't find anything else!
