### ISSUE TITLE
Analyze Google Analytics 

### ISSUE THREAD

**Issue by dbranchini** [cul-it/wp-cul-main#5]
There aren't Epics in GitHub projects, so this is a large issue/task. Let's start with this and then as @manolobevia addresses this, we can add more detailed and smaller tasks as needed.

**Comment by manolobevia** [comment]
## Google Analytics (GA) for Main Library site

> Google Analytics (GA) Date Range resets to the current week. Please select Jan 1, 2019 to present for the reports below, if calendar doesn't reflect `Jan 1, 2019 - present` range date.

There are about [30 reports created](https://analytics.google.com/analytics/web/#/savedreport-overview/savedreport-overview/a8097093w183246266p180795632/_.useg=builtin1,user53To461qRtGgQNbEorjusw&_.advseg=&_.sectionId=/), please focus on the ones below.

**Audience**
- [Overview Audience Global vs Ithaca](https://analytics.google.com/analytics/web/#/savedreport/28o_o6o5QSulmGovEjEp2Q/a8097093w183246266p180795632/_r.dsa=1&_.useg=builtin1,user53To461qRtGgQNbEorjusw&_.advseg=&_.sectionId=&overview-graphOptions.selected=analytics.nthMonth)
- [User flow](https://analytics.google.com/analytics/web/#/report/visitors-flow/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_.sectionId=&_.useg=builtin1&_r.dimension=analytics.sourceMedium/) using source/[medium](https://www.optimizesmart.com/understanding-channels-in-google-analytics/#a2) dimension, this is
different to behavior/content flow. 

**Acquisition**
- [Acquisition Overview](https://analytics.google.com/analytics/web/#/savedreport/QhAUFisjRV-ooxgraNSHDQ/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_r.dsa=1&_.useg=builtin1,user53To461qRtGgQNbEorjusw&_.advseg=&_.sectionId=/)
(Global vs Ithaca)
- [Acquisition from direct traffic landing pages](https://analytics.google.com/analytics/web/#/report/acquisition-channels/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_.sectionId=&_.useg=builtin1,user53To461qRtGgQNbEorjusw&_.advseg=&_r.dsa=1&_r.drilldown=analytics.trafficChannel:Direct/)
- [Acquisition Channels](https://analytics.google.com/analytics/web/#/savedreport/0ux60Dt9ToGGqFaYzG_w_Q/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_r.dsa=1&_r.drilldown=analytics.trafficChannel:Referral&_.useg=builtin1,user53To461qRtGgQNbEorjusw&_.advseg=&_.sectionId=&explorer-table.secSegmentId=analytics.medium&explorer-table.plotKeys=%5B%5D/)

**Behavior**
- [Behavior Overview](https://analytics.google.com/analytics/web/#/savedreport/Ldk3G_CkSMyWR3hsJ-qYjw/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_.useg=builtin1,user53To461qRtGgQNbEorjusw&_.advseg=&_.sectionId=&_r.dsa=1/)
- [Behavior flow - All users](https://analytics.google.com/analytics/web/#/report/content-engagement-flow/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_.sectionId=&_.useg=builtin1&_r.activeSegmentId=user53To461qRtGgQNbEorjusw)
- [Behavior flow - Ithaca users](https://analytics.google.com/analytics/web/#/report/content-engagement-flow/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_.sectionId=&_.useg=user53To461qRtGgQNbEorjusw&_r.activeSegmentId=user53To461qRtGgQNbEorjusw)

**Site Content**

- [All Pages](https://analytics.google.com/analytics/web/#/savedreport/hdEusNq2Q-mrkyzJtG2keA/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_r.dsa=1&_r.tabId=explorer&_.useg=builtin1,user53To461qRtGgQNbEorjusw&_.advseg=&_.sectionId=&explorer-segmentExplorer.segmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D/)
- [Navigation Summary](https://analytics.google.com/analytics/web/#/report/content-pages/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_.sectionId=&_.useg=builtin1&_r.tabId=navigationsummary/)
- [All Landing Pages](https://analytics.google.com/analytics/web/#/savedreport/yPMAOSmqTcm1D_4GFmJ-Zg/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_r.dsa=1&_.sectionId=&_.useg=builtin1&_.advseg=/)
- [Exit pages](https://analytics.google.com/analytics/web/#/savedreport/qcZk3o1sQamEdWvxyz5UBQ/a8097093w183246266p180795632/_u.date00=20190101&_u.date01=20210815&_.sectionId=&_.useg=builtin1&_.advseg=&_r.dsa=1/)

**Comment by manolobevia** [comment]
## Google Data Studio reports for main and unit sites

I have created the reports below for all units to see what users are interested in and find patterns with the use of main library.

The reports display basic metrics, global most visited pages, most visited pages in Ithaca, global most visited landing pages, most visited landing pages in Ithaca, source/medium users access our sites, and referrals.

- [**Main Library**](https://datastudio.google.com/s/u7zjJEQoGH8)

- [Law Library](https://datastudio.google.com/s/hFFAnahrdzY])
- [Mathematics](https://datastudio.google.com/s/uyoezJXZ3WQ)
- [OlinUris Library WP](https://datastudio.google.com/s/ulfN2IKFVxQ)
- [OlinUris Library Drupal](https://datastudio.google.com/s/vxs5bbeLs0k)
- [Music Library](https://datastudio.google.com/s/pIpu12_x2Rw)
- [Rare Library](https://datastudio.google.com/s/sHAX3Pp5uYE)
- [Vet Library](https://datastudio.google.com/s/hmeVi0K9DPw)
- [Mann Library Locomotive](https://datastudio.google.com/u/0/reporting/b5c488f4-f25b-418e-bc54-057a4f8b2819/page/D0MXC)
- [Mann Library WP](https://datastudio.google.com/s/k0BvoM0YhTg)
- [Africana Library](https://datastudio.google.com/s/h-_0AZSx78w)
- [Catherwood Library](https://datastudio.google.com/s/goyHiqm6ASw)
- [Management Library](https://datastudio.google.com/s/jOIM4id17hA)
- [Hotel Library](https://datastudio.google.com/s/vhQ0IalxZa0)
- [FineArts Library](https://datastudio.google.com/s/hAbulO0uK5A)
- [Engineering Library](https://datastudio.google.com/s/lJUjc66bXRk)
- [Asia Library](https://datastudio.google.com/s/hQ_OSJs9Dq8)
- [PSL Library](https://datastudio.google.com/s/hKKSHroumg8)
- [Annex Library](https://datastudio.google.com/s/vv6uN9-cfew)

**Comment by manolobevia** [comment]
@dbranchini I will be adding notes to each report.
