### ISSUE TITLE
Finalize cards for first round of hybrid/open card sort

### ISSUE THREAD

**Issue by dbranchini** [cul-it/wp-cul-main#60]
Notes from internal breakout rooms and discussion:
https://cornell.box.com/s/g50dzvkad1nubd98q7y24h47zvf24klf

**Comment by kevinkidwell** [comment]
Potential Cards:

- About Us
- News
- Events
- Staff
- Collections
- Libraries
- Citation Management
- Instruction
- Workshops
- Equipment
- Spaces
- Borrowing
- Textbooks
- Course Reserves
- Research
- Ask a Librarian

**Comment by kevinkidwell** [comment]
Link to the initial study before the Usability Working Group Meeting: https://ows.io/os/qnj4161r

UWG will be looking at how easy the system is to use, what instructions may need added or adjusted, and if they believe any content areas may not be represented that could be key in this exercise.
